# Generated by Django 5.1.3 on 2024-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phno', models.IntegerField()),
                ('micr', models.IntegerField()),
                ('ifsc', models.EmailField(max_length=254)),
            ],
        ),
    ]
