# Generated by Django 5.1.3 on 2024-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_loan',
            name='ifsc',
            field=models.CharField(max_length=20),
        ),
    ]
